// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lynazqbbinnxbsseysvf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx5bmF6cWJiaW5ueGJzc2V5c3ZmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU4MTc3MDksImV4cCI6MjA1MTM5MzcwOX0.9sQcoVwjYlonBnYxzJOt4KBBFXIJW3RZFXOd5VlsUGM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);